### ISSUE TITLE
forever list says "No forever processes running"

### ISSUE THREAD

**Issue by yeldarby** [foreverjs/forever#483] opened 2013-10-17 22:55 UTC
I'm starting a forever instance on server boot via root's crontab.

    @reboot /usr/local/bin/forever start -w --watchDirectory /home/ubuntu/code/path/to/my/files /home/ubuntu/code/path/to/my/files/index.js

But although the script is running (I can hit the server via port 80) I can't get its logs or restart it or anything because forever doesn't recognize that it's running.

    ubuntu@ip-10-168-82:~$ ps aux | grep forever
    root       902  4.1  2.3 969836 39824 ?        Ssl  22:49   0:03 /usr/local/bin/node /usr/local/lib/node_modules/forever/bin/monitor /home/ubuntu/code/path/to/my/files/index.js
    ubuntu    1165  0.0  0.0   8156   956 pts/0    S+   22:50   0:00 grep --color=auto forever
    ubuntu@ip-10-168-82:~$ sudo forever list
    info:    No forever processes running
    ubuntu@ip-10-168-82:~$ forever list
    info:    No forever processes running

It works properly if I run it directly using `sudo forever...` (I can see the process with `sudo forever list`) but when it runs from root's crontab on boot it gets lost somewhere.

**Comment by bgerd** [comment] 2015-02-28 06:55
In the case this helps anybody, I was having the same problem when starting forever in an init script ... and paying careful attention to $HOME when executing forever was the solution:

For my distro (openwrt), the root's $HOME environment variable hadn't yet been set to its final value (defined in /etc/profile). I also couldn't find a way to set /sbin/init's initial environment variables (e.g. no /etc/default/init) ... not that I felt safe changing it. 

My hackish/workaround was to temporarily set $HOME to the root's final value just to execute 'forever start' in the init script ... and everything now works (e.g. 'forever list' and 'forever stop') from the command line.

**Comment by chrischalstrom** [comment] 2015-03-05 04:05
This is happening to me as well, even with the -p flag set correctly.  I am using Vagrant and Puppet to exec ```forever start ./myserver.js```.  I then ssh into the box, ```forever list``` and see that it reports nothing running, even though when I curl my socket, I get the expected output.

I have to ```sudo su - root``` and then ```forever list``` to see the forever process that got started up.

**Comment by Gerst20051** [comment] 2015-06-24 17:17
:+1:

**Comment by terry-permeance** [comment] 2015-12-02 02:27
If using init.d scripts, pass in HOME:

    sudo HOME=/var/cache/my-app -u my-user forever list

**Comment by indexzero** [comment] 2015-12-15 21:03
Duplicate of #415.

**Closed by indexzero** 2015-12-15 21:03 UTC
Labels: next-major
