### ISSUE TITLE
`forever stop 0` stops all processes

### ISSUE THREAD

**Issue by vladh** [foreverjs/forever#814] opened 2016-02-22 17:05 UTC
I just took down an entire production server due to this.

Steps:
1. `forever start a`
2. `forever start b`
3. `forever stop 0`

All processes are then killed.

**Comment by egirshov** [comment] 2016-02-25 09:57
I believe this is the same as #699 which is apparently already fixed in the master. Sad that there is not update published to npm yet

**Comment by fresheneesz** [comment] 2016-04-14 05:49
Ugh really? Why is this still open? This is a huge freaking problem...

**Comment by ultimate-tester** [comment] 2016-05-17 17:03
This issue should be marked as a duplicate of #699 
Unfortunately the issue still exists because the latest code is not released to npm yet.

**Comment by fresheneesz** [comment] 2016-05-17 18:32
I recently switched to pm2 - SO much better. Screw this waiting for years for huge bugs to be fixed.

**Comment by vladh** [comment] 2016-05-17 18:54
We also switched to pm2.

**Comment by indexzero** [comment] 2016-05-26 00:55
This was fixed in `forever@0.15.2`

**Closed by indexzero** 2016-05-26 00:55 UTC
