### ISSUE TITLE
Current working directory for absolute paths

### ISSUE THREAD

**Issue by gabrielf** [foreverjs/forever#647] opened 2014-11-27 08:51 UTC
Hi!

I have read some of the issues regarding current working directory and I know about the --workingDir option but I must say that I prefer the old behaviour.

I expect the following:

```bash
cd /foo
forever start /web/myapp/server.js
```

To give server.js /foo as its current working directory since that's forever's current working directory. I don't expect it to get / as current working directory.

I realise this is not a backwards compatible change but neither was the change from /foo to / but it was done anyway.

**Comment by indexzero** [comment] 2016-05-26 00:18
Duplicate of #270.

**Closed by indexzero** 2016-05-26 00:18 UTC
Labels: needs-review
