### ISSUE TITLE
Duplicate log entries

### ISSUE THREAD

**Issue by chovy** [foreverjs/forever#499] opened 2013-11-24 03:52 UTC
Duplicate log entries are happening again --- https://github.com/nodejitsu/forever/issues/212

I still have this problem.

```
forever start -l ~/log/app.log -o ~/log/app.log -e ~/log/app.log -a --sourceDir ~/www/app app.js

$ npm list forever -g
/usr/local/lib
└── forever@0.10.9
```

**Comment by indexzero** [comment] 2015-12-15 21:09
Duplicate of #373. As a point of process we are now locking all duplicate issues. Please continue the discussion on #373 if you are interested.

**Closed by indexzero** 2015-12-15 21:09 UTC

**Comment by indexzero** [comment] 2015-12-15 21:11
FYI I believe this is by design right now since `-l` is the combined log of `-o` and `-e` so you're telling forever to log twice. Regardless we should be smarter about user input that we get for log file names.
