### ISSUE TITLE
Forever doesn't wait for script to stop when using killSignal

### ISSUE THREAD

**Issue by andreyst** [foreverjs/forever#528] opened 2014-02-08 23:21 UTC
Hi, 

I am trying to achieve the following: when I am stopping running script with some graceful signal like SIGUSR1 and they consume it and finish what they are doing, I want forever to wait until scripts finish and not quit right away. Right now scripts continue working in background, but there's no (reliable) way to wait for them to finish. 

The reason I want to achieve this is that I am running simple long-running (kinda) php scripts with forever and when deploying I want to gracefully shutdown them and only then continue to update files and restart forever. With current situation I am not able to do that - forever quits right after sending kill signal and build script goes on.

This is how I was testing it:
1. Create php file: https://gist.github.com/andreyst/8891788
2. Run it with forever:
forever -c php --killSignal=SIGUSR1 test.php
3. Stop it:
forever stopall --killSignal=SIGUSR1
4. Forever quits immediately.

Desired behavior: after 3 forever waits, until script really finishes (OR kills it on killTTL, which, by the way, isn't in cli parameters), only then reports success.

It is actually kind of easy to fix. The reason of this is that when we call common.kill in monitor.js:369, we pass it a callback to call and around common.js:48-52 we see that is calls callback() immediately after calling process.kill (not waiting for it to finish). Simply subscribing on child's exit and calling desired callback on this event fixed the problem on test runs. 

The reason why I am not sending a pull request is because fixing this would require more knowledge about logic that is happening in there and more complex fix, since it should account on killing by TTL, not killing at all and so on, and I don't know enough about code to fix it. But anyway looks easy, though.

**Comment by indexzero** [comment] 2015-12-15 21:07
Duplicate of #385. As a point of process we are now locking all duplicate issues. Please continue the discussion on #385 if you are interested.

**Closed by indexzero** 2015-12-15 21:07 UTC
