### ISSUE TITLE
logging to files -o -e not working

### ISSUE THREAD

**Issue by foobar8675** [foreverjs/forever#508] opened 2013-12-15 05:10 UTC
I'm following the help file pretty closely, but I'm not able to get the node console (stderr/stdout) to my log files (~/logs/out.log, ~logs/err.log) . I am however getting the output from forever to ~/logs/forever.log

/usr/bin/forever start -m 5 app.js -o ~/logs/out.log -e ~/logs/err.log &> ~/logs/forever.log

when looking at the process forever starts, I'm seeing the -o and -e options appended to the node process, but I don't see any documentation on those options

/usr/local/bin/node /home/ec2-user/sipi/app.js -o /home/ec2-user/logs/out.log -e /home/ec2-user/logs/err.log

if anyone has any suggestions, it would be much appreciated.

**Comment by markstos** [comment] 2015-06-30 00:23
This is a dupe of #442 .

`forever` is working as documented. Check out the "usage" line seen when you run `forever --help`:

```
usage: forever [action] [options] SCRIPT [script-options]
```

Your logging options appear *after* your script name. Thus, they are interpreted as options to your script not options to the `forever` action. 

I recommend that this issue be closed.

**Closed** 2015-06-30 01:16 UTC
