### ISSUE TITLE
Using SIGINT, desire to shutdown with async calls

### ISSUE THREAD

**Issue by colinmathews** [foreverjs/forever#489] opened 2013-11-01 16:46 UTC
I am using the option to send a custom kill signal to my process like so:

``` 
forever start --killSignal SIGINT my-script.js
``` 

This is great, but my process needs to handle SIGINT signals with a few asynchronous calls for a graceful shutdown. What's happening now is my process receives the SIGINT signal and somehow my process dies as soon as control flow returns from that event handler. 

Instead, I'd like to do something like this in my app:

```
process.on('SIGINT', function(){
    shutdownGracefullyAsync(function(){
        process.exit();
    });
});
``` 

Thanks for any help!

**Comment by indexzero** [comment] 2015-12-15 21:06
Duplicate of #3 85.

**Comment by indexzero** [comment] 2015-12-15 21:06
Duplicate of #385.

**Closed by indexzero** 2015-12-15 21:06 UTC
