### ISSUE TITLE
.foreverignore

### ISSUE THREAD

**Issue by Snorlock** [foreverjs/forever#663] opened 2015-01-07 21:32 UTC
There doesnt exists alot of documentation on this.
Where can i find this?

**Comment by NawarA** [comment] 2015-02-04 23:33
I got it working. Add .foreverignore in the directory you're watching, then add

\*\*.log\*\* 

to the file, or whatever file pattern you'd like to ignore. Thats it. I'm using this now

**Comment by indexzero** [comment] 2015-07-24 06:53
Duplicate of #590. A pull-request for this would be very welcome. It just follows standard ignore syntax like `.gitignore` or `.npmignore`.

**Closed by indexzero** 2015-07-24 06:53 UTC

**Comment by mikeatlas** [comment] 2016-02-22 23:43
Is it really necessary to ask for documentation PRs from others for this small feature?

**Comment by ilanbiala** [comment] 2016-02-23 04:37
Not really sure why @indexzero can't do the docs...if it's so simple then someone who maintains the package really should have written the initial docs as a template for contributors.

**Comment by indexzero** [comment] 2016-02-23 07:35
PRs welcome to documenation
