### ISSUE TITLE
If creation of ~/.forever fails, no error but CLI stops working (i.e. forever list says "No forever processes running")

### ISSUE THREAD

**Issue by tjunnone** [foreverjs/forever#415] opened 2013-05-05 22:48 UTC
If ~/.forever cannot be created while starting as a daemon (and it always tries to, see issue #414), the daemon still starts and everything looks OK and there's nothing to indicate the failure in the logs.

After this however, "forever list" will give: "No forever processes running".
"forever stop" will give: "Forever cannot find process with index: myScript"

I noticed this because when I start Forever from a init script, there's no HOME environment and it tries to write to /root/.forever which it doesn't have permissions for. In addition to obeying the -p parameter, I think there should be an error in the log and perhaps the daemon should even fail to start since it becomes uncontrollable from the cli.

**Comment by indexzero** [comment] 2015-12-15 21:04
Duplicate of #483.

**Comment by xprt64** [comment] 2016-02-17 11:31
I had the same issue: I added an init script that started a node.js application with PM2 but `pm2 list` showed no application running although `ps aux | grep node` listed the process correctly. 
**The solution in my case was to start the init script AFTER the network**; I think the sockets were needed for communication between pm2 instances . 
This is my working init script (notice `$network` at `Required-Start` line):
```
#! /usr/bin/php
<?php
#
### BEGIN INIT INFO
# Provides:          crm
# Required-Start:    $remote_fs $syslog $network $mysql $apache2 $cron $pm2
# Required-Stop:     $remote_fs $syslog $network $mysql $apache2 $cron $pm2
# Should-Start:      $network $time
# Should-Stop:       $network $time
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description:  blah blah blah
# Description:       blah blah blah 
### END INIT INFO
#


require 'startup.php';
```

**Comment by swapnilgt** [comment] 2016-08-19 16:49
Any solutions for this yet?

**Comment by JulianNorton** [comment] 2017-02-08 22:12
3 years later, still an issue.

**Comment by petercunha** [comment] 2017-10-03 05:20
Please fix this...

**Comment by meherchandan** [comment] 2019-02-05 07:33
Any update on this one? I am still facing this issue

**Comment by kibertoad** [comment] 2019-02-05 07:37
Will check it today, sorry!

**Comment by kibertoad** [comment] 2019-02-05 22:32
@meherchandan @tjunnone @petercunha Please review https://github.com/foreverjs/forever/pull/1017

**Comment by petercunha** [comment] 2019-02-05 22:42
Thank you! @kibertoad

**Closed** 2019-02-26 23:30 UTC
Labels: next-major

**Comment by kibertoad** [comment] 2019-03-31 12:20
New version is out with a fix!
