### ISSUE TITLE
Restartall should follow an incremental pattern

### ISSUE THREAD

**Issue by MrDHat** [foreverjs/forever#810] opened 2016-02-14 12:02 UTC
Currently, whenever we push new code, we do a `forever restartall` so that new code gets loaded. Now, the problem is that it restarts all the forever processes at once, which causes the service to be unavailable for some seconds (depending on the time taken to stop and start the process).

A fix for this would to restart the instances one-by-one. So, if say, there are 4 processes, it restarts the first process and does nothing to other processes while the first one restarts. After first process is restarted, it should move to the next instance and so on..

This would ensure that there is absolutely no downtime (which I think goes with the philosophy of forever :smile:  )

What do you guys think about this?

**Comment by indexzero** [comment] 2016-05-26 01:08
Not opposed, but this is a duplicate of #602.

**Closed by indexzero** 2016-05-26 01:08 UTC
