### ISSUE TITLE
Can you please clarify the 3 different log files?

### ISSUE THREAD

**Issue by getify** [foreverjs/forever#700] opened 2015-04-15 20:20 UTC
> -l  LOGFILE      Logs the forever output to LOGFILE

> -o  OUTFILE      Logs stdout from child script to OUTFILE

> -e  ERRFILE      Logs stderr from child script to ERRFILE

The documentation doesn't seem to clarify what the difference between `LOGFILE` and `OUTFILE` is. Can you please clarify this in the documentation?

I am seeing that basically all my script's `stdout` output goes to both `LOGFILE` and `OUTFILE`, so I'm not seeing/understanding the difference between the two.

Is `stderr` output going to go to both `ERRFILE` and `OUTFILE`?

**Comment by markstos** [comment] 2015-06-30 00:34
Fellow user here. I created a minimal manual test and also reviewed the code.  The log file specified by `-l` includes logs from the child's STDOUT and STDERR as well as logging generated directly by forever. However, it appears that it may only have logging directed to it when using `forever start` (daemon mode) as opposed to plain `forever` (long-running-process mode). 

The documentation should be updated to clarify this, although #384 makes a reasonable case that `-l` shouldn't be including the child's STDOUT and STDERR, but only forever's logging. It's true that a user can always direct all 3 output streams to the same file, but it's not really practical to start with the current merged stream and split it back out into multiple streams.

**Comment by indexzero** [comment] 2016-05-26 00:52
This is definitely one of the most confusing things about forever today. Going to close this as a duplicate of #373 in the meantime which is an earlier question about the same logs related topic.

**Closed by indexzero** 2016-05-26 00:52 UTC
