### ISSUE TITLE
It doesn't catch my keys

### ISSUE THREAD

**Issue by dvisockas** [foreverjs/forever#655] opened 2014-12-18 09:33 UTC
When I start want to start forever server I write forever start application.js --pidFile forever.pid
But it doesn't write anything to the pid file. It got suspicious and I tried to run script so that warning would fo away. 
Round #2: forever start application.js --pidFile forever.pid --minUptime 5000 --spinSleepTime 5000
Aaand warnings of minUptime and spinSleepTime didn't go away.
Am I doing something wrong or it is a bug?

**Comment by indexzero** [comment] 2016-05-26 00:17
Duplicate of #421.

**Closed by indexzero** 2016-05-26 00:17 UTC
