### ISSUE TITLE
Feature request: Allow specifying a script to run when client exits via CLI

### ISSUE THREAD

**Issue by diegovar** [foreverjs/forever#171] opened 2011-11-23 17:44 UTC
I'd like to be able to do something like the following:

forever start -exit emailCrash.js app.js 

Where the script emailCrash.js is called when forever detects that app.js is dead for good (that is, it's been revived the maximum number of times or is spinning).

**Comment by cyrilchapon** [comment] 2015-05-18 09:10
Any update / workaround on this ?

**Comment by indexzero** [comment] 2015-12-15 20:58
Duplicate of #437.

**Closed by indexzero** 2015-12-15 20:58 UTC
Labels: duplicate

**Comment by fidergo-stephane-gourichon** [comment] 2017-10-26 21:05
This does not look like a duplicate of #437 (mixed start/restart command), rather a duplicate of #301 .
