### ISSUE TITLE
feature request : notify when script stop

### ISSUE THREAD

**Issue by m4mum** [foreverjs/forever#474] opened 2013-10-02 06:51 UTC
Hi

We are using forever and it works great!

Whenever our js file crash, forever restart them, however if it can notify on e-mail as well, it will be great!

Raxit

**Comment by Geoffzable** [comment] 2015-06-22 07:12
Any update on this?

**Comment by px751** [comment] 2015-08-06 12:49
+1

**Comment by muzaparoff** [comment] 2015-08-09 14:33
+

**Comment by indexzero** [comment] 2015-12-15 20:57
Duplicate of #171.

**Closed by indexzero** 2015-12-15 20:57 UTC
Labels: duplicate

**Comment by JuliaRakitina** [comment] 2018-11-26 11:59
+1

**Comment by ThBastos** [comment] 2020-09-11 14:40
+1
