### ISSUE TITLE
No logging by default

### ISSUE THREAD

**Issue by akamensky** [foreverjs/forever#384] opened 2013-02-12 12:43 UTC
This report actually covers three issues:

1. 
My application STDOUT goes to forever log. Which i don't expect at all since there are separate options for this `-l` for forever log and `-o` for scripts STDOUT. In other words anything i output with console.log goes to both `-o` log and `-l` log.

What i would expect to see there is that my script output goes only to `-o` and in `-l` i will see only info about processes started, stopped, restarted after crash etc with timestamps of course...

2.
Currently if forever log option `-l` is not specified, then it starts new log in `/home/username/.forever/randomFilename`.

My app generates quite large amount of output to STDOUT, which is needed for development. This caused gigantic log file which i was unable to open. (size was ~200 MB) Seems to me that there is no limit for log file size now, which IMO it should have.

3.
In my case closely related to 2.
I think better option would be is to default all log options not to be logged into a file or to send them to /dev/null. For now each time i run my servers i have to do `-l /dev/null`

**Comment by markstos** [comment] 2015-06-30 00:21
I'll also note that the `-l` command doesn't document precisely which log output it handles. It's not explicit that in addition to the forever-specific laws it also includes the STDOUT and STDERR of the child process.

**Comment by indexzero** [comment] 2015-12-15 20:41
Duplicate of #373.

**Closed by indexzero** 2015-12-15 20:41 UTC

**Comment by sunyonggang** [comment] 2016-01-20 14:03
This is really an interesting topic.
:runner: 
In my advice, ```-l``` can be turncated cyclically would be better, if my log can grow very quick, i can set a specific time.
