### ISSUE TITLE
Generic error message when log path isn't specified

### ISSUE THREAD

**Issue by stith** [foreverjs/forever#514] opened 2014-01-06 14:22 UTC
```
deploydir=/var/www/something/htdocs
logdir=/var/www/something/logs
$ forever --minUptime=1000ms --spinSleepTime=1000ms --sourceDir=$deploydir --pidFile=/var/run/tester.pid -o $logdir/tester.out.log -e $logdir/tester.err.log -o $logdir/tester.log -a -v -d app.js

fs.js:418
  binding.open(pathModule._makeLong(path),
          ^
TypeError: path must be a string
    at Object.fs.open (fs.js:418:11)
    at WriteStream.open (fs.js:1652:6)
    at new WriteStream (fs.js:1642:10)
    at Object.fs.createWriteStream (fs.js:1606:10)
    at exports.attach (/usr/local/lib/node_modules/forever/node_modules/forever-monitor/lib/forever-monitor/plugins/logger.js:27:43)
    at Object.bootstrap (/usr/local/lib/node_modules/forever/node_modules/forever-monitor/lib/forever-monitor/monitor.js:33:27)
    at exports.App (/usr/local/lib/node_modules/forever/node_modules/forever-monitor/node_modules/broadway/lib/broadway/app.js:47:21)
    at new exports.Monitor (/usr/local/lib/node_modules/forever/node_modules/forever-monitor/lib/forever-monitor/monitor.js:119:16)
    at Object.forever.start (/usr/local/lib/node_modules/forever/lib/forever.js:381:17)
    at /usr/local/lib/node_modules/forever/lib/forever/cli.js:535:27
```

After a bit of brainstorming I realized that I forgot the -l option, but it seems like Forever could be more helpful in pointing that out. I don't see it specified anywhere that -l is a required option as well, so maybe this is just a documentation issue.

**Comment by indexzero** [comment] 2015-12-15 21:12
Duplicate of #490.

**Closed by indexzero** 2015-12-15 21:12 UTC
Labels: confirmed
