### ISSUE TITLE
File descriptors not persisted in forever

### ISSUE THREAD

**Issue by ifeltsweet** [foreverjs/forever#322] opened 2012-07-20 19:22 UTC
I have tried `cat /dev/null > /root/.forever/xxxx.log` and it will remove contents of the file BUT only until the next line is written to log, after which all the contents comeback. `forever cleanlogs` didn't help either.

**Comment by acidjazz** [comment] 2015-04-15 06:07
Did we find an ultimate solution for this?

```bash
pi@garry1:~/.forever$ ls -la *.log | wc -l
91
pi@garry1:~/.forever$ cd ..
pi@garry1:~$ du -sh .forever/
26M	.forever/
```

**Comment by indexzero** [comment] 2015-12-15 21:00
Duplicate of #106.

**Closed by indexzero** 2015-12-15 21:00 UTC
Labels: duplicate
