### ISSUE TITLE
`forever list` doesn't see other user's processes, not even with sudo

### ISSUE THREAD

**Issue by dandv** [foreverjs/forever#544] opened 2014-03-31 17:50 UTC
I have a process launched by user `dandv`, and it shows up under `forever list`.

But if I run `forever list` while logged in as another user, it shows `No forever processes running`. `sudo forever list` shows the same. I've even tried running the command from `/` or from `/home/dandv` - same result.

**Comment by jasonswearingen** [comment] 2015-06-10 14:21
i had this issue, Here is my resolution.

I am running forever via crontab ```@reboot``` on a non-admin account called ```serviceaccount```

I could not see forever when logging into that non-admin account via ```sudo -u serviceaccount bash```  

but once i used ```su serviceaccount``` I was able to use ```forever list``` no problem

**Comment by Gerst20051** [comment] 2015-06-24 17:19
:+1:

**Comment by indexzero** [comment] 2015-12-15 20:43
Duplicate of #415.

**Closed by indexzero** 2015-12-15 20:43 UTC
Labels: duplicate
