### ISSUE TITLE
-p option does nothing

### ISSUE THREAD

**Issue by eric-tucker** [foreverjs/forever#658] opened 2014-12-30 14:46 UTC
Either it should be removed from the help screen or it should do what the FOREVER_ROOT environment variable was (for some ridiculous reason) added to do: https://github.com/foreverjs/forever/pull/469

It's absurd that the -p option wasn't just fixed rather than adding another (undocumented) option.

**Comment by scarby** [comment] 2015-01-12 15:39
I have also observed this behavior. The -p option should really work needing to use environment variables to set these things can cause problems with init scripts. At the moment we have simply worked around the issue but it is less than ideal

**Comment by indexzero** [comment] 2016-05-26 00:23
Duplicate of #414

**Closed by indexzero** 2016-05-26 00:23 UTC
